### PR TITLE
updates

### PR DESCRIPTION
**Pull request by jumanjiman**
* docker now ignores the .git dir
* add gitignore
* be specific about which version of centos to build upon
* install hp rpms via yum from official repos
* pin hp rpms at a specific version

### CODE REVIEW

**Comment by mazad01** [comment]
Hey @jumanjiman this looks great! Thanks for the updates. Is it ready to be shipped?

**Comment by jumanjiman** [comment]
> Is it ready to be shipped?

yep!

**Comment by jumanjiman** [comment]
thanks @mazad01 !

**Comment by mazad01** [comment]
Thank you!

**Pull request merged**
